version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "8000:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    # command: prometheus --config.file=prometheus.yml

volumes:
  grafana-data:
networks:
  monitoring: