version: "3.8"

services:
  bun-app:
    build: .
    container_name: bun-server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules