global:
  scrape_interval: 5s  # Collect metrics every 5 seconds

scrape_configs:
  - job_name: "bun-app"
    metrics_path: "/metrics"  # Expects Bun to expose metrics at `/metrics`
    static_configs:
      - targets: ["127.0.0.1:3000"]  # Use only the hostname or IP address